services:
    '@enhavo/media/loader/MediaLoader':
        chunk: 'form'
        arguments:
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/core/Router'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/core/Translator'
        tags:
            - 'enhavo_app.form'

    '@enhavo/media/image-cropper/ImageCropperApp':
        chunk: 'image-cropper'
        arguments:
            - 'param:data.format'
            - '@enhavo/app/frame/EventDispatcher'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/app/action/ActionManager'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/core/Translator'
            - '@enhavo/app/vue/VueRegistry'

    '@enhavo/media/components/ImageCropperComponent.vue':
        chunk: 'image-cropper'
        static: true

    '@enhavo/media/components/ImageCropperStageComponent.vue':
        chunk: 'vue'
        static: true
        tags:
            - { name: vue.component, component: 'image-cropper' }
