imports:
    - path: '../*'

services:
    '@enhavo/media/loader/MediaLoader':
        chunk: 'form'
        arguments:
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/core/Router'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/app/translation/Translator'
        tags:
            - 'enhavo_app.form'

    '@enhavo/media/image-cropper/ImageCropperApp':
        chunk: 'image-cropper'
        arguments:
            - 'param:data.format'
            - '@enhavo/app/frame/FrameEventDispatcher'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/app/action/ActionManager'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/app/translation/Translator'
            - '@enhavo/app/vue/VueRegistry'

    '@enhavo/media/components/ImageCropper.vue':
        chunk: 'image-cropper'
        static: true

    '@enhavo/media/components/ImageCropperStage.vue':
        chunk: 'vue'
        static: true
        tags:
            - { name: vue.component, component: 'image-cropper' }

    '@enhavo/media/controllers/MediaStyleController':
        chunk: controller
        static: true
        tags:
            - { name: stimulus.controller, key: 'media-style' }
