imports:
    - path: '../*'

services:
    '@enhavo/media/loader/MediaLoader':
        chunk: 'form'
        arguments:
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/core/Router'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/app/translation/Translator'
        tags:
            - 'enhavo_app.form'

    '@enhavo/media/manager/ImageCropperManager':
        import: ImageCropperManager
        chunk: 'image-cropper'
        arguments:
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/app/action/ActionManager'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/app/translation/Translator'
            - '@enhavo/app/routing/Router'
        tags:
            - { name: vue.service, service: 'imageCropperManager', reactive: true }

    '@enhavo/media/components/MediaImageCropper.vue':
        chunk: 'vue'
        static: true
        tags:
            - { name: vue.component, component: 'media-image-cropper' }

    '@enhavo/media/controllers/MediaStyleController':
        chunk: controller
        static: true
        tags:
            - { name: stimulus.controller, key: 'media-style' }

    '@enhavo/media/action/MediaCropAction':
        import: MediaCropAction
        chunk: 'image-cropper'
        arguments:
            - '@enhavo/media/manager/ImageCropperManager'
        tags:
            - { name: enhavo_app.action }
